# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

matrix:
  include:
    - os: linux
      dist: xenial
      language: cpp
      before_install:
        - sudo apt-get update
      install:
        - build/ci/linux/install_dependencies
        # None of the packaged channels are new enough for the current state
        # of FDE, so for now clone master instead.
        #- build/ci/install_flutter $TRAVIS_BUILD_DIR/..
        - git clone -b master https://github.com/flutter/flutter.git $TRAVIS_BUILD_DIR/../flutter
        - build/ci/linux/install_gn bin
      before_script:
        - export PATH=$PATH:$TRAVIS_BUILD_DIR/bin
      script:
        - make -C example/linux_fde

    - os: osx
      language: objective-c
      xcode_project: example/macos_fde/ExampleEmbedder.xcodeproj
      xcode_scheme: ExampleEmbedder
      install:
        # None of the packaged channels are new enough for the current state
        # of FDE, so for now clone master instead.
        #- build/ci/install_flutter $TRAVIS_BUILD_DIR/..
        - git clone -b master https://github.com/flutter/flutter.git $TRAVIS_BUILD_DIR/../flutter
      # Override the build command to remove 'test'. The example embedder
      # doesn't have any unit tests, and while a UI test to ensure that it
      # launches would be useful, that's currently broken by:
      # https://travis-ci.community/t/issue-cant-run-macos-ui-tests-with-xcode10-1-image/1445
      script:
        - set -o pipefail && xcodebuild -project $TRAVIS_XCODE_PROJECT -scheme $TRAVIS_XCODE_SCHEME build | xcpretty

