name: testbed
description: A test project for flutter-desktop-embedding.

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # FDE plugins.
  # Note: In an actual project, these would be included via 'git:' reference,
  # rather than 'path:', as described in the plugins README.
  menubar:
    path: ../plugins/menubar
  window_size:
    path: ../plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
