name: testbed
description: A test project for flutter-desktop-embedding.

environment:
  sdk: '>=2.0.0 <3.0.0'
  # The testbed interacts with build scripts on the Flutter side that are not
  # yet stable, so it requires a very recent version of Flutter.
  # This version will increase regularly as the build scripts change.
  flutter: '>=1.10.2-pre.54'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

  # FDE plugins.
  # Note: In an actual project, these would be included via 'git:' reference,
  # rather than 'path:', as described in the plugins README.
  file_chooser:
    path: ../plugins/file_chooser
  menubar:
    path: ../plugins/menubar
  window_size:
    path: ../plugins/window_size
  # Plugins that have had their implementations upstreamed.
  shared_preferences: ^0.5.8
  url_launcher: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
